# -*- coding: utf-8 -*-

TEST_CASES = [
    # Еб / prefixes / forms
    ("ебать", True),
    ("ебал", True),
    ("ебало", True),
    ("еблище", True),
    ("ебучий", True),
    ("еблан", True),
    ("ебобо", True),
    ("заебал", True),
    ("заебись", True),
    ("съебался", True),
    ("съебись", True),
    ("выебал", True),
    ("выебон", True),
    ("выебываться", True),
    ("подъебал", True),
    ("подъеб", True),
    ("наебал", True),
    ("наебалово", True),
    ("проебал", True),
    ("проеб", True),
    ("разъебал", True),
    ("разъеб", True),
    ("отъебись", True),
    ("отъебал", True),
    ("въебал", True),
    ("доебался", True),
    ("переебал", True),
    ("уебан", True),
    ("уебок", True),
    ("уебище", True),
    ("поебать", True),
    ("приебался", True),
    
    # Хуй / prefixes / forms
    ("хуй", True),
    ("хуя", True),
    ("хуевый", True),
    ("хуёвый", True),
    ("хуйня", True),
    ("хуета", True),
    ("хуесос", True),
    ("хуила", True),
    ("похуй", True),
    ("похую", True),
    ("нахуй", True),
    ("нахуя", True),
    ("нихуя", True),
    ("дохуя", True),
    ("схуяли", True),
    ("захуярил", True),
    ("отхуярил", True),
    ("охуел", True),
    ("ахуел", True),
    ("охуеть", True),
    ("ахуеть", True),
    ("охуенно", True),
    ("ахуенно", True),
    ("прихуел", True),
    
    # Пизд / prefixes / forms
    ("пизда", True),
    ("пиздец", True),
    ("пиздатый", True),
    ("пиздеть", True),
    ("пиздит", True),
    ("пиздюк", True),
    ("спиздил", True),
    ("спиздить", True),
    ("распиздяй", True),
    ("допизделся", True),
    ("впизду", True),
    ("отпиздить", True),
    ("напиздел", True),
    
    # Бля
    ("блять", True),
    ("блядь", True),
    ("бля", True),
    ("блядина", True),
    ("блядский", True),
    
    # Сука (should not trigger false positives on regular words)
    ("сука", True),
    ("сучка", True),
    ("сучара", True),
    ("сучий", True),
    
    # False positives test (MUST BE FALSE)
    ("посуда", False),
    ("рисунок", False),
    ("барсук", False),
    ("сукно", False),
    ("сосуд", False),
    ("кусок", False),
    ("брусок", False),
    ("носок", False),
    ("песок", False),
    ("лесок", False),
    ("рубль", False),
    ("колебание", False),
    ("стебель", False),
    ("хлеб", False),
    ("ослабление", False),
    ("ястреб", False),
    ("парикмахер", False),
    ("страховка", False),
    ("застрахован", False),
    ("выхухоль", False),
    ("скипидар", False),
    ("педагог", False),
    ("эпидермис", False),
    ("употреблять", False),
    ("оскорблять", False),
    ("гребля", False),
    ("грабли", False),
    ("шапка", False),
    
    # Other profanities
    ("пидор", True),
    ("пидорас", True),
    ("пидарас", True),
    ("пидрила", True),
    ("педик", True),
    ("гондон", True),
    ("гандон", True),
    ("мудак", True),
    ("мудила", True),
    ("шлюха", True),
    ("шалава", True),
    ("шаболда", True),
    ("мразь", True),
    ("мразота", True),
    ("ублюдок", True),
    ("чмо", True),
    ("чмошник", True),
    ("долбоеб", True),
    ("долбоёб", True),
    ("долбаеб", True),
    ("залупа", True),
    ("похер", True),
    ("нахер", True),
    ("херня", True),
    ("дрочить", True),
    
    # Toxic multi-words
    ("сын шлюхи", True),
    ("сын собаки", True),
    ("мамку ебал", True),
    ("твой рот ебал", True),
    ("mq", True),
    ("rnq", True),
    
    # Translit / English
    ("ebat", True),
    ("pizdec", True),
    ("nahuy", True),
    ("blyat", True),
    ("fuck", True),
    ("fucking", True),
    ("bitch", True),
    ("whore", True),
    ("asshole", True),
]
